class Mapas:
    def populate_graph(g, map):
    #Todas as distâncias estão em quilometros
        if (map == '1'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)

        elif (map == '2'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
            
        elif (map == '3'):
            g.add_edge("Balança", "Campo do Gerês", 1)
            g.add_edge("Campo do Gerês", "Carvalheira", 1)
            g.add_edge("Carvalheira", "Chamoim e Vilar", 1)
            g.add_edge("Chamoim e Vilar", "Chorense e Monte", 1)
            g.add_edge("Chorense e Monte", "Cibões e Brufe", 1)
            g.add_edge("Cibões e Brufe", "Covide", 1)
            g.add_edge("Covide", "Gondoriz", 1)
            g.add_edge("Gondoriz", "Moimenta", 1)
            g.add_edge("Moimenta", "Ribeira", 1)
            g.add_edge("Ribeira", "Rio Caldo", 1)
            g.add_edge("Rio Caldo", "Souto", 1)
            g.add_edge("Souto", "Valdosende", 1)
            g.add_edge("Valdosende", "Vilar da Veiga", 1)
            g.add_edge("Vilar da Veiga", "Balança", 1)

            #Para a heurística foi considerado a distância em linha reta até á rua mais central (Balança)
            g.add_heuristica("Balança", 0)
            g.add_heuristica("Campo do Gerês", 1)
            g.add_heuristica("Vilar da Veiga", 1)
            g.add_heuristica("Valdosende", 1.5)
            g.add_heuristica("Carvalheira", 1.4)
            g.add_heuristica("Souto", 2.0)
            g.add_heuristica("Chamoim e Vilar", 2.3)
            g.add_heuristica("Rio Caldo", 2.4)
            g.add_heuristica("Ribeira", 3.1)
            g.add_heuristica("Chorense e Monte", 3.7)
            g.add_heuristica("Cibões e Brufe", 4)
            g.add_heuristica("Moimenta", 4.5)
            g.add_heuristica("Gondoriz", 5)
            g.add_heuristica("Covide", 4.6)
        
        elif(map == '4'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)
            g.add_edge("Central", "Rua das Forças Armadas", 11.5)
            g.add_edge("Rua das Forças Armadas", "Avenida José Afonso", 49.4)
            g.add_edge("Rua do Seixal", "Rua das Forças Armadas", 6.7)
            g.add_edge("Rua do Seixal", "Travessa Dom Lopes", 8.8)
            g.add_edge("Rua do Seixal", "Rua dos Padrões", 8.9)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
            g.add_heuristica("Avenida José Afonso", 46.6)
            g.add_heuristica("Rua do Seixal", 15.9)
            g.add_heuristica("Travessa Dom Lopes", 23.5)