class Mapas:
    def populate_graph(g, map):
    #Todas as distâncias estão em quilometros
        if (map == '1'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)

        elif (map == '2'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
        
        elif(map == '3'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)
            g.add_edge("Central", "Rua das Forças Armadas", 11.5)
            g.add_edge("Rua das Forças Armadas", "Avenida José Afonso", 49.4)
            g.add_edge("Rua do Seixal", "Rua das Forças Armadas", 6.7)
            g.add_edge("Rua do Seixal", "Travessa Dom Lopes", 8.8)
            g.add_edge("Rua do Seixal", "Rua dos Padrões", 8.9)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
            g.add_heuristica("Avenida José Afonso", 46.6)
            g.add_heuristica("Rua do Seixal", 15.9)
            g.add_heuristica("Travessa Dom Lopes", 23.5)

        elif(map == '4'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)
            g.add_edge("Central", "Rua das Forças Armadas", 11.5)
            g.add_edge("Rua das Forças Armadas", "Avenida José Afonso", 49.4)
            g.add_edge("Rua do Seixal", "Rua das Forças Armadas", 6.7)
            g.add_edge("Rua do Seixal", "Travessa Dom Lopes", 8.8)
            g.add_edge("Rua do Seixal", "Rua dos Padrões", 8.9)
            g.add_edge("Rua dos Padrões", "Rua da Escola", 17.1)
            g.add_edge("Rua dos Padrões", "Rua Manuel Caldas", 19.9)
            g.add_edge("Rua dos Padrões", "Rua dos Corujos", 5.0)
            g.add_edge("Rua dos Corujos", "Rua Manuel Caldas", 28.9)
            g.add_edge("Rua dos Corujos", "Rua Nova de Santa Cruz", 79.4)
            g.add_edge("Avenida José Afonso", "Travessa Dom Lopes", 16.8)
            g.add_edge("Rua dos Corujos", "Central", 8.9)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
            g.add_heuristica("Avenida José Afonso", 46.6)
            g.add_heuristica("Rua do Seixal", 15.9)
            g.add_heuristica("Travessa Dom Lopes", 23.5)
            g.add_heuristica("Rua da Escola", 8.8)
            g.add_heuristica("Rua Manuel Caldas", 12.2)
            g.add_heuristica("Rua dos Corujos", 21.0)

        elif(map == '5'):
            g.add_edge("Avenida São Pedro", "Central", 35.7)
            g.add_edge("Central", "Rua das Forças Armadas", 12.0)
            g.add_edge("Rua das Forças Armadas", "Beco dos Unidos", 28.1)
            g.add_edge("Rua das Forças Armadas", "Rua dos Padrões", 40.0)
            g.add_edge("Rua das Forças Armadas", "Avenida São Pedro", 9.3)
            g.add_edge("Rua dos Padrões", "Central", 12.3)
            g.add_edge("Avenida São Pedro", "Rua Humberto Delgado", 4.0)
            g.add_edge("Rua Humberto Delgado", "Central", 4.0)
            g.add_edge("Rua de Pesqueiras", "Rua Humberto Delgado", 32.0)
            g.add_edge("Rua Nova de Santa Cruz", "Rua de Pesqueiras", 63.1)
            g.add_edge("Rua de Pesqueiras", "Central", 5.5)
            g.add_edge("Central", "Avenida São Pedro", 6.0)
            g.add_edge("Central", "Rua das Forças Armadas", 11.5)
            g.add_edge("Rua das Forças Armadas", "Avenida José Afonso", 49.4)
            g.add_edge("Rua do Seixal", "Rua das Forças Armadas", 6.7)
            g.add_edge("Rua do Seixal", "Travessa Dom Lopes", 8.8)
            g.add_edge("Rua do Seixal", "Rua dos Padrões", 8.9)
            g.add_edge("Rua dos Padrões", "Rua da Escola", 17.1)
            g.add_edge("Rua dos Padrões", "Rua Manuel Caldas", 19.9)
            g.add_edge("Rua dos Padrões", "Rua dos Corujos", 5.0)
            g.add_edge("Rua dos Corujos", "Rua Manuel Caldas", 28.9)
            g.add_edge("Rua dos Corujos", "Rua Nova de Santa Cruz", 79.4)
            g.add_edge("Avenida José Afonso", "Travessa Dom Lopes", 16.8)
            g.add_edge("Rua dos Corujos", "Central", 8.9)
            g.add_edge("Rua da Escola", "Caminho do Real", 2.1)
            g.add_edge("Rua do Seixal", "Caminho do Real", 8.2)
            g.add_edge("Rua Moura", "Caminho do Real", 12.3)
            g.add_edge("Rua Moura", "Rua do Couto", 18.3)
            g.add_edge("Rua da Coutada", "Rua do Couto", 56.7)
            g.add_edge("Rua da Coutada", "Travessa Dom Lopes", 47.3)
            g.add_edge("Rua Humberto Delgado", "Rua Paula Furtado", 4.7)
            g.add_edge("Avenida São Pedro", "Rua Paula Furtado", 6.7)
            g.add_edge("Rua Figueira da Foz", "Rua Paula Furtado", 18.0)
            g.add_edge("Avenida de Coimbra", "Rua Paula Furtado", 12.8)
            g.add_edge("Avenida de Coimbra", "Rua Humberto Delgado", 34.4)

            #Para a heurística foi considerado a distância em linha reta até á central
            g.add_heuristica("Beco dos Unidos", 37.6)
            g.add_heuristica("Rua das Forças Armadas", 11.5)
            g.add_heuristica("Rua dos Padrões", 12.0)
            g.add_heuristica("Central", 0)
            g.add_heuristica("Avenida São Pedro", 34.9)
            g.add_heuristica("Rua Humberto Delgado", 4.0)
            g.add_heuristica("Rua de Pesqueiras", 34.3)
            g.add_heuristica("Rua Nova de Santa Cruz", 94.4)
            g.add_heuristica("Avenida José Afonso", 46.6)
            g.add_heuristica("Rua do Seixal", 15.9)
            g.add_heuristica("Travessa Dom Lopes", 23.5)
            g.add_heuristica("Rua da Escola", 8.8)
            g.add_heuristica("Rua Manuel Caldas", 12.2)
            g.add_heuristica("Rua dos Corujos", 21.0)
            g.add_heuristica("Caminho do Real", 11.1)
            g.add_heuristica("Rua Moura", 19.5)
            g.add_heuristica("Rua do Couto", 23.8)
            g.add_heuristica("Rua da Coutada", 33.9)
            g.add_heuristica("Rua Paula Furtado", 12.9)
            g.add_heuristica("Rua Figueira da Foz", 16.9)
            g.add_heuristica("Avenida de Coimbra", 25.7)